// Register
POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}
###

// Login
POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "JoeBiden",
  "password": "biden@123"
}

###

// Tweets Feed
GET http://localhost:3000/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzQxNDA5MjQwfQ.YOK_vT5LkIt0T7ST8IlNwgH5sXiWxl46deNBucOvZJQ

###

// Following List
GET http://localhost:3000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzQxNDA5MjQwfQ.YOK_vT5LkIt0T7ST8IlNwgH5sXiWxl46deNBucOvZJQ

###

// Followers List
GET http://localhost:3000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzQxNDA5MjQwfQ.YOK_vT5LkIt0T7ST8IlNwgH5sXiWxl46deNBucOvZJQ

###

// Specific Tweet
GET http://localhost:3000/tweets/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzQxNDA5MjQwfQ.YOK_vT5LkIt0T7ST8IlNwgH5sXiWxl46deNBucOvZJQ

###

// Users Who Liked the tweet
GET http://localhost:3000/tweets/1/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzQxNDA5MjQwfQ.YOK_vT5LkIt0T7ST8IlNwgH5sXiWxl46deNBucOvZJQ


###

// Get Replies to the tweet
GET http://localhost:3000/tweets/1/replies/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzQxNDA5MjQwfQ.YOK_vT5LkIt0T7ST8IlNwgH5sXiWxl46deNBucOvZJQ


###

// Get User's Tweets
GET http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzQxNDA5MjQwfQ.YOK_vT5LkIt0T7ST8IlNwgH5sXiWxl46deNBucOvZJQ

###

// Create a Tweet
POST http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzQxNDA5MjQwfQ.YOK_vT5LkIt0T7ST8IlNwgH5sXiWxl46deNBucOvZJQ
Content-Type: application/json

{
  "tweet": "Hello, this is my first tweet!"
}

###

// Delete a Tweet
DELETE http://localhost:3000/tweets/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzQxNDA5MjQwfQ.YOK_vT5LkIt0T7ST8IlNwgH5sXiWxl46deNBucOvZJQ